[package]
name = "cargo-loki-apk"
version = "0.1.4"
authors = ["The Loki Authors", "Pierre Krieger <pierre.krieger1708@gmail.com>", "Philip Alldredge <philip@philipalldredge.com>", "Fedor Logachev <not.fl3@gmail.com>"]
license = "MIT"
description = "Cargo subcommand that allows you to build Android packages for projects using lokinit."
repository = "https://github.com/loki-chat/cargo-loki-apk.git"
edition = "2018"

[dependencies]
cargo = "0.62.0"
cargo-util = "0.1"
clap = "3.1.0"
itertools = "0.8.2"
dirs = "2.0.2"
anyhow = "1.0"
multimap = "0.8.0"
serde = "1.0.104"
toml = "0.5.5"
glob = "0.3"

[dev-dependencies]
assert_cmd = "0.12.0"
